run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gocyclo
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - govet
    - gosimple
    - typecheck

linters-settings:
  gocyclo:
    min-complexity: 30
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  # Fail CI on any issue - no exclusions for unused variables
  exclude-rules:
    # Exclude errcheck for test files
    - path: _test\.go
      linters:
        - errcheck
    # Exclude errcheck for Close, Setenv, Unsetenv calls (common practice)
    - linters:
        - errcheck
      text: "Error return value of `.*(Close|Setenv|Unsetenv).*` is not checked"
    # Exclude unusedwrite in test files (struct fields set for test setup)
    - path: _test\.go
      linters:
        - govet
      text: "unusedwrite:"
